apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- route.yaml
- secrets

namespace: opendatahub

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: prometheus
  app.kubernetes.io/part-of: prometheus

generatorOptions:
  disableNameSuffixHash: true

vars:
  - name: namespace
    objref:
      kind: Prometheus
      name: odh-monitoring
      apiVersion: monitoring.coreos.com/v1
    fieldref:
      fieldpath: metadata.namespace

configurations:
  - params.yaml
