apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- secrets

namespace: opendatahub

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: prometheus
  app.kubernetes.io/part-of: prometheus

generatorOptions:
  disableNameSuffixHash: true
