apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../servicemonitors

resources:
  - cluster-monitoring-role-binding.yaml
  - prometheus-monitoring-role-binding.yaml
  - prometheus.yaml
