---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odh-prometheus-monitoring-rb
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: PLACEHOLDER_NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: odh-prometheus-monitoring
